controller_list:
  - name: fake_mani_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_end_controller
    joints:
      - bh_j11_joint
      - bh_j12_joint
      - bh_j13_joint
      - bh_j21_joint
      - bh_j22_joint
      - bh_j23_joint
      - bh_j32_joint
      - bh_j33_joint